services:
  mysql:
    image: mysql:8.0
    container_name: laravel_live_mysql
    ports:
      - "33061:3306"
    environment:
      MYSQL_DATABASE: laravel_live
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - laravel_live_mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-ularavel", "-plaravel"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: laravel_live_redis
    ports:
      - "63791:6379"
    volumes:
      - laravel_live_redis_data:/data

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: laravel_live_mediamtx
    ports:
      - "1935:1935"
      - "8888:8888"
      - "8889:8889"
      - "8554:8554"

volumes:
  laravel_live_mysql_data:
  laravel_live_redis_data:
