<?php

namespace App\PatternLab;

use App\PatternLab\Support\PatternDefinition;

final class PatternRegistry
{
    private const CATEGORIES = [
        'creational' => [
            'key' => 'creational',
            'name' => 'Creational',
            'name_cn' => '创建型',
            'description' => '关注对象创建过程，把创建细节从业务代码中拆出来。',
            'directory' => 'Creational',
            'doc_directory' => 'creational',
        ],
        'structural' => [
            'key' => 'structural',
            'name' => 'Structural',
            'name_cn' => '结构型',
            'description' => '关注类和对象之间的组合关系，让结构变化更容易控制。',
            'directory' => 'Structural',
            'doc_directory' => 'structural',
        ],
        'behavioral' => [
            'key' => 'behavioral',
            'name' => 'Behavioral',
            'name_cn' => '行为型',
            'description' => '关注对象之间的职责分配、流程协作和行为变化。',
            'directory' => 'Behavioral',
            'doc_directory' => 'behavioral',
        ],
        'laravel-specific' => [
            'key' => 'laravel-specific',
            'name' => 'Laravel Specific',
            'name_cn' => 'Laravel 常用模式',
            'description' => '关注 Laravel 后端项目里高频出现的分层、队列、验证和事件组织方式。',
            'directory' => 'LaravelSpecific',
            'doc_directory' => 'laravel-specific',
        ],
    ];

    private const PATTERNS = [
        [
            'key' => 'simple-factory',
            'name' => 'Simple Factory',
            'name_cn' => '简单工厂',
            'class_name' => 'SimpleFactory',
            'category' => 'creational',
            'difficulty' => 'easy',
            'status' => 'todo',
            'summary' => '通过一个工厂类根据参数创建不同对象，隐藏对象创建细节。',
            'problem' => '业务层直接根据类型 new 多个导出器时，创建细节会散落在 Controller 或 Service 中，新增类型需要反复修改分支。',
            'scenario' => '根据导出类型创建不同导出器。',
            'common_usage' => [
                '报表导出',
                '文件生成',
                '消息格式化',
                '第三方服务客户端创建',
                '简单对象创建分支',
            ],
            'exercise_goals' => [
                '定义统一导出器接口',
                '设计工厂类',
                '根据类型返回不同导出器',
                '避免在业务层直接写多个 new',
            ],
            'exercise_content' => [
                'title' => '报表导出器选择器',
                'description' => '你正在实现一个报表导出入口，用户传入导出类型 `csv`、`excel`、`pdf` 或 `json`，系统选择对应导出器处理同一份指标数据。',
                'requirements' => [
                    '设计一个统一导出器契约，接收行数据和导出选项。',
                    '通过工厂根据导出类型返回对应导出器，调用方不要直接 new 具体导出器。',
                    '在 Exercise.php::run() 中演示选择 `excel` 导出 3 行指标数据，并返回一段说明文本。',
                    '补充测试覆盖四种导出类型和未知类型的处理。',
                ],
            ],
            'suggested_classes' => [
                'ExporterInterface.php',
                'CsvExporter.php',
                'ExcelExporter.php',
                'PdfExporter.php',
                'JsonExporter.php',
                'ExporterFactory.php',
            ],
            'laravel_connection' => '适合放在 Service 或 Support 层，Laravel 容器可以负责工厂本身的创建。',
        ],
        [
            'key' => 'factory-method',
            'name' => 'Factory Method',
            'name_cn' => '工厂方法',
            'class_name' => 'FactoryMethod',
            'category' => 'creational',
            'difficulty' => 'medium',
            'status' => 'todo',
            'summary' => '把对象创建延迟到子类，由具体工厂决定创建哪种产品。',
            'problem' => '当每个产品族都有独立创建规则时，简单工厂会不断膨胀，创建逻辑难以按渠道拆分。',
            'scenario' => '不同通知渠道创建不同消息发送器。',
            'common_usage' => [
                '通知系统',
                '支付渠道',
                '文件存储驱动',
                '第三方平台接入',
                '多渠道业务处理',
            ],
            'exercise_goals' => [
                '定义通知发送器接口',
                '定义工厂抽象',
                '由不同具体工厂创建发送器',
                '对比简单工厂和工厂方法区别',
            ],
            'exercise_content' => [
                'title' => '多渠道通知发送器创建',
                'description' => '你正在实现一个通知中心，不同通知渠道由不同工厂创建发送器，用于发送订单状态变更提醒。',
                'requirements' => [
                    '定义通知发送器契约，至少考虑 email、sms、webhook、in-app 四种渠道。',
                    '定义抽象工厂入口，让每个具体工厂负责创建自己渠道的发送器。',
                    '在 Exercise.php::run() 中演示创建短信发送器并生成一条订单发货通知。',
                    '补充测试对比不同工厂创建出的发送器类型和输出内容。',
                ],
            ],
            'suggested_classes' => [
                'NotificationSenderInterface.php',
                'NotificationFactory.php',
                'EmailNotificationFactory.php',
                'SmsNotificationFactory.php',
                'WebhookNotificationFactory.php',
            ],
            'laravel_connection' => '可以和 Laravel 服务容器绑定配合，用不同工厂封装不同渠道的创建规则。',
        ],
        [
            'key' => 'abstract-factory',
            'name' => 'Abstract Factory',
            'name_cn' => '抽象工厂',
            'class_name' => 'AbstractFactory',
            'category' => 'creational',
            'difficulty' => 'hard',
            'status' => 'todo',
            'summary' => '创建一组相关或相互依赖的对象，而不指定具体类。',
            'problem' => '同一渠道需要创建多种协作对象时，如果逐个判断渠道，产品族一致性很难维护。',
            'scenario' => '不同支付渠道创建一组支付相关对象。',
            'common_usage' => [
                '支付系统',
                '多租户主题组件',
                '多数据库方言适配',
                '多云服务 SDK 适配',
                '多产品族对象创建',
            ],
            'exercise_goals' => [
                '定义支付组件族接口',
                '定义抽象工厂',
                '为不同渠道创建具体工厂',
                '理解产品族概念',
            ],
            'exercise_content' => [
                'title' => '支付渠道组件族',
                'description' => '你正在实现一个支付接入层，支付宝和微信支付都需要成套创建支付请求构造器、回调解析器和退款处理器。',
                'requirements' => [
                    '定义支付组件族契约，确保同一渠道的请求、回调、退款组件来自同一个工厂。',
                    '至少设计 `alipay` 和 `wechat` 两组具体工厂。',
                    '在 Exercise.php::run() 中演示选择 `wechat` 工厂并列出本次创建的组件。',
                    '补充测试验证不会混用不同支付渠道的组件族。',
                ],
            ],
            'suggested_classes' => [
                'PaymentComponentFactoryInterface.php',
                'PaymentRequestBuilderInterface.php',
                'PaymentCallbackParserInterface.php',
                'RefundProcessorInterface.php',
                'AlipayPaymentFactory.php',
                'WechatPaymentFactory.php',
            ],
            'laravel_connection' => '适合封装多渠道 SDK 组合对象，Laravel 容器可以按配置解析具体工厂。',
        ],
        [
            'key' => 'builder',
            'name' => 'Builder',
            'name_cn' => '建造者模式',
            'class_name' => 'Builder',
            'category' => 'creational',
            'difficulty' => 'medium',
            'status' => 'todo',
            'summary' => '把复杂对象的构建过程拆成多个步骤，使构建过程更清晰。',
            'problem' => '复杂查询对象参数很多时，构造函数会变长，调用方难以看出每个参数的含义。',
            'scenario' => '构建复杂报表查询条件。',
            'common_usage' => [
                '查询条件构建',
                '报表配置构建',
                'API 请求参数构建',
                '消息体构建',
                '复杂 DTO 构建',
            ],
            'exercise_goals' => [
                '设计报表查询对象',
                '设计 Builder',
                '分步骤设置查询条件',
                '避免构造函数参数过多',
            ],
            'exercise_content' => [
                'title' => '复杂报表查询条件构建器',
                'description' => '你正在实现一个指标报表查询功能，用户可以选择指标、维度、时间范围、过滤条件、排序和分页参数。',
                'requirements' => [
                    '设计一个报表查询条件对象，表达 metric、dimension、date range、filters、sort、page。',
                    '使用 Builder 分步骤设置查询条件，避免构造函数参数过长。',
                    '在 Exercise.php::run() 中构建“最近 30 天按地区统计收入”的查询条件。',
                    '补充测试验证必填项、默认分页和链式构建结果。',
                ],
            ],
            'suggested_classes' => [
                'ReportQuery.php',
                'ReportQueryBuilder.php',
                'ReportFilter.php',
                'ReportSort.php',
            ],
            'laravel_connection' => 'Laravel Query Builder 和部分配置对象都体现了分步骤构建复杂对象的思想。',
        ],
        [
            'key' => 'prototype',
            'name' => 'Prototype',
            'name_cn' => '原型模式',
            'class_name' => 'Prototype',
            'category' => 'creational',
            'difficulty' => 'medium',
            'status' => 'todo',
            'summary' => '通过复制已有对象来创建新对象。',
            'problem' => '复杂配置对象重新构造成本高，直接复用又容易互相污染状态。',
            'scenario' => '复制已有图表配置，并在副本上修改部分字段。',
            'common_usage' => [
                '图表模板复制',
                '报表模板复制',
                '表单模板复制',
                '权限配置复制',
                '复杂对象克隆',
            ],
            'exercise_goals' => [
                '理解浅拷贝和深拷贝',
                '复制已有配置对象',
                '修改副本不影响原对象',
                '思考 PHP clone 的边界',
            ],
            'exercise_content' => [
                'title' => '图表配置模板复制',
                'description' => '你正在实现一个仪表盘配置功能，用户可以复制已有图表模板，再修改标题、数据源和筛选条件生成新图表。',
                'requirements' => [
                    '设计图表配置对象，包含标题、图表类型、数据源、筛选条件和序列配置。',
                    '通过复制已有配置生成新配置，修改副本时不能影响原模板。',
                    '在 Exercise.php::run() 中复制一个柱状图模板并改成“华东收入趋势”。',
                    '补充测试区分浅拷贝和深拷贝对嵌套配置的影响。',
                ],
            ],
            'suggested_classes' => [
                'ChartConfig.php',
                'ChartSeries.php',
                'ChartConfigCloner.php',
            ],
            'laravel_connection' => '常见于模板、配置、DTO 复制场景，需要特别注意对象属性里的嵌套引用。',
        ],
        [
            'key' => 'singleton',
            'name' => 'Singleton',
            'name_cn' => '单例模式',
            'class_name' => 'Singleton',
            'category' => 'creational',
            'difficulty' => 'easy',
            'status' => 'todo',
            'summary' => '保证一个类只有一个实例，并提供全局访问点。',
            'problem' => '需要全局共享同一对象时，随意创建实例可能导致状态不一致，但手写单例也会带来测试困难。',
            'scenario' => '全局配置读取器。',
            'common_usage' => [
                '配置管理',
                '日志管理',
                '连接管理',
                '但在 Laravel 中通常由服务容器管理生命周期',
            ],
            'exercise_goals' => [
                '理解单例写法',
                '理解单例的测试困难',
                '理解全局状态问题',
                '理解为什么 Laravel 中通常不推荐手写单例',
            ],
            'exercise_content' => [
                'title' => '应用运行参数读取器',
                'description' => '你正在实现一个运行参数读取器，用来读取当前练习环境配置，并观察同一请求内共享实例带来的便利和风险。',
                'requirements' => [
                    '设计一个最小配置读取入口，能读取 app name、timezone 或自定义练习参数。',
                    '实现时记录为什么手写单例会带来全局状态和测试隔离问题。',
                    '在 Exercise.php::run() 中演示两次读取同一配置，并说明它们是否来自同一实例。',
                    '补充测试时优先思考如何重置状态，以及 Laravel 容器 singleton 是否更合适。',
                ],
            ],
            'suggested_classes' => [
                'ConfigReader.php',
                'ConfigReaderSingleton.php',
            ],
            'laravel_connection' => 'Laravel 通常使用服务容器 singleton 绑定管理生命周期，而不是手写静态单例。',
        ],
        [
            'key' => 'adapter',
            'name' => 'Adapter',
            'name_cn' => '适配器模式',
            'class_name' => 'Adapter',
            'category' => 'structural',
            'difficulty' => 'easy',
            'status' => 'todo',
            'summary' => '把不兼容的接口转换成客户端期望的接口。',
            'problem' => '第三方 SDK 方法名、参数和返回值不一致时，业务层直接调用会被外部接口污染。',
            'scenario' => '统一不同第三方短信平台接口。',
            'common_usage' => [
                '第三方 SDK 接入',
                '支付平台接入',
                '短信平台接入',
                '地图服务接入',
                '文件存储服务接入',
                '老系统接口兼容',
            ],
            'exercise_goals' => [
                '定义统一短信发送接口',
                '为不同平台创建适配器',
                '屏蔽不同 SDK 方法差异',
                '让业务层只依赖统一接口',
            ],
            'exercise_content' => [
                'title' => '统一短信平台发送接口',
                'description' => '你正在实现短信发送功能，阿里云、腾讯云和华为云 SDK 的方法名、参数和返回结构都不一致。',
                'requirements' => [
                    '定义统一短信发送接口，输入手机号、模板编号和模板变量。',
                    '为至少两个模拟短信平台创建适配器，把不同 SDK 调用转换成统一结果。',
                    '在 Exercise.php::run() 中演示业务层只依赖统一接口发送验证码短信。',
                    '补充测试验证不同平台返回结果被规范化成同一种结构。',
                ],
            ],
            'suggested_classes' => [
                'SmsSenderInterface.php',
                'AliyunSmsAdapter.php',
                'TencentSmsAdapter.php',
                'HuaweiSmsAdapter.php',
            ],
            'laravel_connection' => '适合放在 Infrastructure 或 Support 层，并通过容器把统一接口绑定到具体适配器。',
        ],
        [
            'key' => 'bridge',
            'name' => 'Bridge',
            'name_cn' => '桥接模式',
            'class_name' => 'Bridge',
            'category' => 'structural',
            'difficulty' => 'hard',
            'status' => 'todo',
            'summary' => '把抽象部分和实现部分分离，使它们可以独立变化。',
            'problem' => '消息类型和发送渠道两个维度一起继承时，类数量会随组合数快速膨胀。',
            'scenario' => '消息内容类型和发送渠道分离。',
            'common_usage' => [
                '消息系统',
                '多维度组合业务',
                '多平台渲染',
                '多渠道发送',
                '报表展示方式和导出方式分离',
            ],
            'exercise_goals' => [
                '避免类型和渠道组合爆炸',
                '理解两个变化维度',
                '让消息类型和发送渠道独立扩展',
            ],
            'exercise_content' => [
                'title' => '消息类型与发送渠道组合',
                'description' => '你正在实现消息系统，验证码、营销消息、系统告警三类内容都可能通过邮件、短信、Webhook 或站内信发送。',
                'requirements' => [
                    '把消息内容类型和发送渠道拆成两个独立变化维度。',
                    '避免创建 `SmsAlertMessage`、`EmailAlertMessage` 这类组合爆炸类。',
                    '在 Exercise.php::run() 中演示“系统告警消息 + Webhook 渠道”的组合。',
                    '补充测试验证新增渠道时不需要修改已有消息类型。',
                ],
            ],
            'suggested_classes' => [
                'Message.php',
                'VerificationMessage.php',
                'AlertMessage.php',
                'MessageChannelInterface.php',
                'EmailChannel.php',
                'SmsChannel.php',
            ],
            'laravel_connection' => '可以把渠道实现交给容器解析，把业务抽象和基础设施实现分开演进。',
        ],
        [
            'key' => 'composite',
            'name' => 'Composite',
            'name_cn' => '组合模式',
            'class_name' => 'Composite',
            'category' => 'structural',
            'difficulty' => 'medium',
            'status' => 'todo',
            'summary' => '把对象组合成树形结构，使单个对象和组合对象可以被一致处理。',
            'problem' => '树结构中叶子节点和父节点处理方式不同，调用方需要不断判断节点类型。',
            'scenario' => '菜单树 / 权限树。',
            'common_usage' => [
                '菜单管理',
                '权限管理',
                '部门组织树',
                '分类树',
                '文件目录树',
                '评论树',
            ],
            'exercise_goals' => [
                '定义统一节点接口',
                '区分叶子节点和组合节点',
                '统一遍历树结构',
                '计算权限或菜单层级',
            ],
            'exercise_content' => [
                'title' => '后台菜单和权限树',
                'description' => '你正在实现后台导航权限树，菜单组、菜单项和按钮权限需要被统一遍历和过滤。',
                'requirements' => [
                    '定义统一节点契约，让叶子节点和组合节点能被一致处理。',
                    '实现菜单组包含子节点，菜单项或按钮作为叶子节点。',
                    '在 Exercise.php::run() 中构建一个“系统管理 > 用户管理 > 新增按钮”的小树。',
                    '补充测试验证树遍历、层级路径和按权限过滤后的结果。',
                ],
            ],
            'suggested_classes' => [
                'MenuNodeInterface.php',
                'MenuItem.php',
                'MenuGroup.php',
                'PermissionNode.php',
            ],
            'laravel_connection' => '适合后台菜单、权限树、分类树等需要递归遍历的数据结构。',
        ],
        [
            'key' => 'decorator',
            'name' => 'Decorator',
            'name_cn' => '装饰器模式',
            'class_name' => 'Decorator',
            'category' => 'structural',
            'difficulty' => 'medium',
            'status' => 'todo',
            'summary' => '在不修改原对象的情况下，动态增加额外功能。',
            'problem' => '缓存、日志、性能统计等横切能力直接写进原服务，会让核心业务逻辑变得混杂。',
            'scenario' => '给报表查询服务增加缓存、日志、性能统计。',
            'common_usage' => [
                'Service 增强',
                '缓存包装',
                '日志包装',
                '性能监控',
                '权限校验',
                'API 客户端增强',
            ],
            'exercise_goals' => [
                '保持原服务接口不变',
                '用装饰器包装原服务',
                '理解装饰器和继承的区别',
                '理解装饰器和代理的区别',
            ],
            'exercise_content' => [
                'title' => '报表查询服务增强',
                'description' => '你正在实现报表查询服务，并希望在不改原服务的情况下增加缓存、日志和耗时统计。',
                'requirements' => [
                    '定义报表查询服务契约，原始服务只负责查询数据。',
                    '用装饰器分别包装缓存、日志和耗时统计能力。',
                    '在 Exercise.php::run() 中演示原始服务被缓存装饰器和日志装饰器包裹后的调用顺序。',
                    '补充测试验证装饰器不改变原服务接口，并能按顺序叠加能力。',
                ],
            ],
            'suggested_classes' => [
                'ReportQueryServiceInterface.php',
                'ReportQueryService.php',
                'CachedReportQueryService.php',
                'LoggedReportQueryService.php',
            ],
            'laravel_connection' => '可通过容器装配服务包装链，也可对客户端、查询服务、导出服务做增强。',
        ],
        [
            'key' => 'facade',
            'name' => 'Facade',
            'name_cn' => '外观模式',
            'class_name' => 'Facade',
            'category' => 'structural',
            'difficulty' => 'easy',
            'status' => 'todo',
            'summary' => '为复杂子系统提供一个简单统一的入口。',
            'problem' => 'Controller 直接协调多个服务时，会暴露过多流程细节，业务入口不够稳定。',
            'scenario' => '订单创建流程统一入口。',
            'common_usage' => [
                '复杂业务流程入口',
                '多服务协调',
                'Controller 调用业务流程',
                '支付流程',
                '报表生成流程',
                '文件上传处理流程',
            ],
            'exercise_goals' => [
                '设计一个高层入口类',
                '隐藏内部多个服务调用',
                '保持 Controller 简洁',
                '理解 Laravel Facade 和 GoF Facade 区别',
            ],
            'exercise_content' => [
                'title' => '订单创建流程统一入口',
                'description' => '你正在实现下单流程，创建订单时需要协调库存、支付单、通知和操作日志多个子系统。',
                'requirements' => [
                    '设计一个高层业务入口，隐藏内部多个服务的调用顺序。',
                    '让 Controller 或 Exercise 只调用一个订单创建入口。',
                    '在 Exercise.php::run() 中演示创建一笔包含两个商品的订单流程摘要。',
                    '补充测试验证入口输出包含订单、库存、支付单和通知步骤。',
                ],
            ],
            'suggested_classes' => [
                'OrderCreationFacade.php',
                'StockService.php',
                'PaymentOrderService.php',
                'NotificationService.php',
                'OperationLogService.php',
            ],
            'laravel_connection' => 'Laravel Facade 是服务容器静态代理风格，不完全等同于 GoF 外观模式。',
        ],
        [
            'key' => 'proxy',
            'name' => 'Proxy',
            'name_cn' => '代理模式',
            'class_name' => 'Proxy',
            'category' => 'structural',
            'difficulty' => 'medium',
            'status' => 'todo',
            'summary' => '通过代理对象控制对真实对象的访问。',
            'problem' => '真实服务访问前后需要权限、缓存、延迟加载等控制时，直接调用真实对象难以统一管理。',
            'scenario' => '远程文件服务访问代理。',
            'common_usage' => [
                '远程服务访问',
                '文件服务',
                'API 客户端',
                '权限控制',
                '缓存代理',
                '延迟加载',
            ],
            'exercise_goals' => [
                '定义真实服务接口',
                '创建代理类',
                '在代理中增加权限或缓存逻辑',
                '理解代理和装饰器区别',
            ],
            'exercise_content' => [
                'title' => '远程文件下载代理',
                'description' => '你正在实现文件下载功能，真实远程文件服务访问前需要做权限检查、元信息缓存和延迟加载。',
                'requirements' => [
                    '定义文件服务契约，真实服务只表达远程读取能力。',
                    '创建代理对象，在访问真实服务前加入权限检查和缓存判断。',
                    '在 Exercise.php::run() 中演示用户下载报表文件前先经过代理校验。',
                    '补充测试验证无权限不会访问真实服务，有缓存时减少远程调用。',
                ],
            ],
            'suggested_classes' => [
                'FileServiceInterface.php',
                'RemoteFileService.php',
                'AuthorizedFileServiceProxy.php',
                'CachedFileServiceProxy.php',
            ],
            'laravel_connection' => '可以代理远程服务客户端、文件服务或昂贵资源访问，并结合中间件或策略做访问控制。',
        ],
        [
            'key' => 'data-mapper',
            'name' => 'Data Mapper',
            'name_cn' => '数据映射模式',
            'class_name' => 'DataMapper',
            'category' => 'structural',
            'difficulty' => 'hard',
            'status' => 'todo',
            'summary' => '把领域对象和数据库持久化逻辑分离。',
            'problem' => '领域对象直接依赖 ORM 时，业务行为和持久化细节会耦合在一起。',
            'scenario' => '将数据库记录和领域对象分离。',
            'common_usage' => [
                '领域驱动设计',
                '复杂业务模型',
                '多数据源映射',
                '避免领域对象依赖 ORM',
                '替代 Active Record 的复杂场景',
            ],
            'exercise_goals' => [
                '理解 Active Record 和 Data Mapper 区别',
                '设计领域对象',
                '设计 Mapper',
                '避免领域对象直接操作数据库',
            ],
            'exercise_content' => [
                'title' => '用户资料领域对象持久化',
                'description' => '你正在实现用户资料模块，领域对象只表达业务属性和行为，数据库读写由 Mapper 负责。',
                'requirements' => [
                    '设计不依赖 Eloquent 的用户资料领域对象。',
                    '设计 Mapper 负责把数据库记录转换成领域对象，并把领域对象保存回记录。',
                    '在 Exercise.php::run() 中演示加载用户资料、修改昵称、准备保存的过程。',
                    '补充测试验证领域对象不直接调用数据库或 ORM。',
                ],
            ],
            'suggested_classes' => [
                'UserProfile.php',
                'UserProfileMapper.php',
                'UserProfileRecord.php',
            ],
            'laravel_connection' => 'Laravel Eloquent 是 Active Record 风格，复杂领域模型中可以额外引入 Mapper 做隔离。',
        ],
        [
            'key' => 'dependency-injection',
            'name' => 'Dependency Injection',
            'name_cn' => '依赖注入',
            'class_name' => 'DependencyInjection',
            'category' => 'structural',
            'difficulty' => 'easy',
            'status' => 'todo',
            'summary' => '把对象依赖从外部传入，而不是在类内部创建。',
            'problem' => '类内部直接 new 依赖会让替换实现、单元测试和组合扩展变困难。',
            'scenario' => '订单服务依赖支付服务、库存服务、通知服务。',
            'common_usage' => [
                'Laravel Service',
                'Controller 构造函数',
                'Job 构造函数',
                'Event Listener',
                'Repository',
                '第三方客户端',
            ],
            'exercise_goals' => [
                '使用构造函数注入',
                '避免在类内部 new 依赖',
                '理解 Laravel 服务容器',
                '理解接口依赖和实现绑定',
            ],
            'exercise_content' => [
                'title' => '订单服务依赖替换',
                'description' => '你正在实现订单提交服务，它依赖支付网关、库存服务和通知服务，但不应在类内部直接创建这些依赖。',
                'requirements' => [
                    '定义订单服务需要的依赖接口，并通过构造函数注入。',
                    '准备真实实现和测试替身的设计位置。',
                    '在 Exercise.php::run() 中用模拟依赖演示提交订单流程。',
                    '补充测试验证替换支付网关实现时不需要修改订单服务。',
                ],
            ],
            'suggested_classes' => [
                'OrderService.php',
                'PaymentServiceInterface.php',
                'StockServiceInterface.php',
                'NotificationServiceInterface.php',
            ],
            'laravel_connection' => 'Laravel 服务容器天然支持构造函数注入和接口绑定，是项目中最常用的模式之一。',
        ],
        [
            'key' => 'fluent-interface',
            'name' => 'Fluent Interface',
            'name_cn' => '流式接口',
            'class_name' => 'FluentInterface',
            'category' => 'structural',
            'difficulty' => 'medium',
            'status' => 'todo',
            'summary' => '通过链式调用让代码表达更接近自然语言。',
            'problem' => '多个配置步骤分散调用时，可读性差；但链式调用过长也会降低调试性。',
            'scenario' => '报表查询条件链式构建。',
            'common_usage' => [
                'Laravel Query Builder',
                'Eloquent 查询',
                '报表查询构建',
                'API 参数构建',
                '表单配置构建',
            ],
            'exercise_goals' => [
                '每个方法返回 $this',
                '链式构建查询配置',
                '理解可读性和调试成本',
                '避免链式调用过长',
            ],
            'exercise_content' => [
                'title' => '报表查询链式 DSL',
                'description' => '你正在实现一个报表查询配置器，让调用方用链式调用表达指标、维度、时间范围、排序和分页。',
                'requirements' => [
                    '设计每个配置方法都返回当前对象或新的配置对象。',
                    '链式调用应能表达 `metric()->groupBy()->between()->sortBy()->paginate()`。',
                    '在 Exercise.php::run() 中构建“收入按城市分组并按金额倒序”的查询配置。',
                    '补充测试验证链式顺序、最终配置和过长链式调用的可读性边界。',
                ],
            ],
            'suggested_classes' => [
                'ReportCriteria.php',
                'ReportCriteriaBuilder.php',
            ],
            'laravel_connection' => 'Laravel Query Builder、Collection 和部分测试 API 都大量使用流式接口。',
        ],
        [
            'key' => 'registry',
            'name' => 'Registry',
            'name_cn' => '注册表模式',
            'class_name' => 'Registry',
            'category' => 'structural',
            'difficulty' => 'medium',
            'status' => 'todo',
            'summary' => '通过一个集中位置保存和获取对象或配置。',
            'problem' => '可用组件、处理器或策略分散定义时，调用方难以发现、查找和统一展示。',
            'scenario' => '统一登记可用报表组件或导出器。',
            'common_usage' => [
                '插件系统',
                '组件系统',
                '策略列表管理',
                '服务查找',
                '配置集中管理',
            ],
            'exercise_goals' => [
                '创建注册表',
                '支持注册、查找、列出',
                '理解注册表和服务容器区别',
                '避免全局状态滥用',
            ],
            'exercise_content' => [
                'title' => '导出器注册表',
                'description' => '你正在实现一个导出器注册中心，系统启动时登记 csv、excel、pdf 导出器，业务运行时按 key 查找。',
                'requirements' => [
                    '设计注册、查找、列出可用导出器的注册表入口。',
                    '处理重复注册、未知 key 和状态禁用的情况。',
                    '在 Exercise.php::run() 中注册三个导出器并查找 `excel`。',
                    '补充测试验证注册表和 Laravel 服务容器的职责边界。',
                ],
            ],
            'suggested_classes' => [
                'ReportComponentRegistry.php',
                'ExporterRegistry.php',
            ],
            'laravel_connection' => '本 PatternLab 的 PatternRegistry 就是元信息注册表的练习入口，但不绑定运行时业务对象。',
        ],
        [
            'key' => 'strategy',
            'name' => 'Strategy',
            'name_cn' => '策略模式',
            'class_name' => 'Strategy',
            'category' => 'behavioral',
            'difficulty' => 'easy',
            'status' => 'todo',
            'summary' => '封装一组可替换算法，使它们可以在运行时切换。',
            'problem' => '同一业务动作存在多套规则时，if/else 会不断膨胀，新增规则容易影响旧规则。',
            'scenario' => '订单运费计算，根据不同配送方式选择不同计算规则。',
            'common_usage' => [
                '支付方式选择',
                '优惠券计算',
                '运费计算',
                '报表导出格式',
                '数据同步策略',
                '第三方接口调用策略',
            ],
            'exercise_goals' => [
                '定义策略接口',
                '实现多个具体策略',
                '创建 Context 类',
                '通过组合替代大量 if/else',
            ],
            'exercise_content' => [
                'title' => '订单运费计算器',
                'description' => '你正在实现订单运费计算功能，不同配送方式有不同计费规则，例如普通快递、加急配送、同城配送和会员免邮。',
                'requirements' => [
                    '定义统一运费计算策略，输入订单金额、重量、距离和会员等级。',
                    '至少设计普通快递、加急配送、同城配送三种策略。',
                    '在 Exercise.php::run() 中演示同一订单切换不同配送方式得到不同运费说明。',
                    '补充测试验证不同策略的选择、边界金额和会员免邮场景。',
                ],
            ],
            'suggested_classes' => [
                'ShippingFeeStrategyInterface.php',
                'NormalShippingStrategy.php',
                'ExpressShippingStrategy.php',
                'SameCityShippingStrategy.php',
                'ShippingFeeContext.php',
            ],
            'laravel_connection' => '可以通过容器、配置或枚举选择具体策略，常用于支付、优惠和导出场景。',
        ],
        [
            'key' => 'observer',
            'name' => 'Observer',
            'name_cn' => '观察者模式',
            'class_name' => 'Observer',
            'category' => 'behavioral',
            'difficulty' => 'easy',
            'status' => 'todo',
            'summary' => '对象状态变化时，自动通知多个依赖对象。',
            'problem' => '主流程直接调用所有后续动作会越来越重，新增动作需要修改核心流程。',
            'scenario' => '订单支付成功后触发多个后续动作。',
            'common_usage' => [
                'Laravel Event / Listener',
                '模型事件',
                '订单状态变化',
                '用户注册成功',
                '支付成功回调',
                '消息通知',
            ],
            'exercise_goals' => [
                '理解事件发布和订阅',
                '解耦事件发生者和响应者',
                '对比 Laravel Event / Listener',
                '避免主流程塞满后续动作',
            ],
            'exercise_content' => [
                'title' => '订单支付成功后续动作',
                'description' => '你正在实现订单支付成功后的扩展点，支付完成后需要发送通知、增加积分、写日志和推送统计数据。',
                'requirements' => [
                    '定义支付成功事件或主题对象，并允许多个观察者订阅。',
                    '每个观察者只处理一个后续动作，不要把所有动作写进支付主流程。',
                    '在 Exercise.php::run() 中演示发布一次订单支付成功事件后触发多个观察者。',
                    '补充测试验证新增观察者不需要修改事件发布方。',
                ],
            ],
            'suggested_classes' => [
                'OrderPaidEvent.php',
                'SendPaymentNotificationListener.php',
                'AddUserPointListener.php',
                'WriteOrderLogListener.php',
            ],
            'laravel_connection' => 'Laravel Event、Listener 和模型事件都体现了观察者思想。',
        ],
        [
            'key' => 'command',
            'name' => 'Command',
            'name_cn' => '命令模式',
            'class_name' => 'Command',
            'category' => 'behavioral',
            'difficulty' => 'medium',
            'status' => 'todo',
            'summary' => '把请求封装成对象，使请求可以排队、记录、撤销或重试。',
            'problem' => '操作直接散落在调用方时，很难记录、排队、重试或统一调度。',
            'scenario' => '后台任务封装。',
            'common_usage' => [
                'Laravel Job',
                'Artisan Command',
                '队列任务',
                '后台操作',
                '批处理任务',
                '可重试任务',
            ],
            'exercise_goals' => [
                '把操作封装为命令对象',
                '设计命令执行入口',
                '理解命令和任务队列的关系',
                '对比 Laravel Job',
            ],
            'exercise_content' => [
                'title' => '后台任务命令对象',
                'description' => '你正在实现后台批处理中心，把导出报表、发送通知、清理缓存等操作封装为可执行命令对象。',
                'requirements' => [
                    '定义命令对象契约，表达 `execute()` 和必要的任务描述。',
                    '设计一个命令执行入口，可以记录执行结果或失败原因。',
                    '在 Exercise.php::run() 中演示执行“导出日报表”命令。',
                    '补充测试验证命令可以被排队、记录和替换执行器。',
                ],
            ],
            'suggested_classes' => [
                'TaskCommandInterface.php',
                'ExportReportCommand.php',
                'SendNotificationCommand.php',
                'CommandBus.php',
            ],
            'laravel_connection' => 'Laravel Job 和 Artisan Command 都可以作为命令模式在框架中的具体应用场景。',
        ],
        [
            'key' => 'chain-of-responsibility',
            'name' => 'Chain of Responsibility',
            'name_cn' => '责任链模式',
            'class_name' => 'ChainOfResponsibility',
            'category' => 'behavioral',
            'difficulty' => 'medium',
            'status' => 'todo',
            'summary' => '让多个处理器按链路依次处理请求，直到请求被处理或链路结束。',
            'problem' => '一串校验或审批步骤写在同一个方法里时，顺序、职责和复用都会变得不清晰。',
            'scenario' => '请求风控校验。',
            'common_usage' => [
                'Laravel Middleware',
                'Pipeline',
                '请求过滤',
                '数据导入校验',
                '风控规则',
                '审批流程',
            ],
            'exercise_goals' => [
                '定义处理器接口',
                '让请求沿链路传递',
                '每个处理器只关注一个职责',
                '对比 Laravel Middleware 和 Pipeline',
            ],
            'exercise_content' => [
                'title' => '登录风控校验链',
                'description' => '你正在实现登录前风控校验，请求需要依次经过账号状态、权限、黑名单和频率限制校验。',
                'requirements' => [
                    '定义处理器契约，每个处理器只判断一个风控规则。',
                    '让请求沿链路传递，某个处理器拒绝时终止后续处理。',
                    '在 Exercise.php::run() 中演示一个被黑名单处理器拦截的登录请求。',
                    '补充测试验证处理顺序、短路行为和全部通过的场景。',
                ],
            ],
            'suggested_classes' => [
                'RiskCheckHandlerInterface.php',
                'LoginCheckHandler.php',
                'PermissionCheckHandler.php',
                'BlacklistCheckHandler.php',
                'RateLimitCheckHandler.php',
            ],
            'laravel_connection' => 'Laravel Middleware 和 Pipeline 都很接近责任链思想。',
        ],
        [
            'key' => 'state',
            'name' => 'State',
            'name_cn' => '状态模式',
            'class_name' => 'State',
            'category' => 'behavioral',
            'difficulty' => 'medium',
            'status' => 'todo',
            'summary' => '对象在不同状态下表现出不同行为，并把状态行为封装到状态类中。',
            'problem' => '状态流转规则散落在 if/else 中时，每个状态可执行的动作和约束都难以维护。',
            'scenario' => '订单状态流转。',
            'common_usage' => [
                '订单系统',
                '审批系统',
                '工单系统',
                '支付单状态',
                '发票状态',
                '任务状态机',
            ],
            'exercise_goals' => [
                '定义状态接口',
                '为每个状态创建类',
                '把状态行为从订单类中拆出',
                '减少状态 if/else',
            ],
            'exercise_content' => [
                'title' => '订单状态流转器',
                'description' => '你正在实现订单状态流转，不同状态下可执行的动作不同，例如待支付、已支付、已发货、已完成和已取消。',
                'requirements' => [
                    '定义状态契约，把每个状态允许的行为放到对应状态类。',
                    '明确哪些状态可以支付、发货、完成或取消。',
                    '在 Exercise.php::run() 中演示订单从待支付到已支付再到已发货的流转摘要。',
                    '补充测试验证非法流转会被拒绝，而不是静默成功。',
                ],
            ],
            'suggested_classes' => [
                'OrderStateInterface.php',
                'PendingPaymentState.php',
                'PaidState.php',
                'ShippedState.php',
                'CancelledState.php',
                'OrderContext.php',
            ],
            'laravel_connection' => '适合复杂订单、工单和审批流程，也可以和枚举、状态机配置结合。',
        ],
        [
            'key' => 'template-method',
            'name' => 'Template Method',
            'name_cn' => '模板方法',
            'class_name' => 'TemplateMethod',
            'category' => 'behavioral',
            'difficulty' => 'medium',
            'status' => 'todo',
            'summary' => '父类定义算法流程骨架，子类实现具体步骤。',
            'problem' => '多个流程步骤大体相同但细节不同，如果复制粘贴，会导致公共流程改动成本高。',
            'scenario' => '不同数据导入流程。',
            'common_usage' => [
                '数据导入',
                '文件处理',
                '报表生成',
                '支付回调处理',
                '定时任务流程',
                '数据清洗流程',
            ],
            'exercise_goals' => [
                '抽象共同流程',
                '子类实现差异步骤',
                '理解继承带来的约束',
                '对比策略模式',
            ],
            'exercise_content' => [
                'title' => '数据导入流程模板',
                'description' => '你正在实现数据导入功能，用户导入、订单导入和商品导入都有读取、校验、转换、保存、生成报告的共同流程。',
                'requirements' => [
                    '定义抽象导入模板，固定共同流程顺序。',
                    '让具体导入类只实现差异步骤，例如字段校验和转换规则。',
                    '在 Exercise.php::run() 中演示用户导入流程执行到生成报告。',
                    '补充测试验证共同流程顺序稳定，子类只替换差异步骤。',
                ],
            ],
            'suggested_classes' => [
                'AbstractImportTemplate.php',
                'UserImport.php',
                'OrderImport.php',
                'ProductImport.php',
            ],
            'laravel_connection' => '适合导入、回调和生成流程，但要控制继承层级，避免父类过重。',
        ],
        [
            'key' => 'specification',
            'name' => 'Specification',
            'name_cn' => '规格模式',
            'class_name' => 'Specification',
            'category' => 'behavioral',
            'difficulty' => 'hard',
            'status' => 'todo',
            'summary' => '把复杂业务判断封装为可组合的规则对象。',
            'problem' => '复杂资格判断写在一个方法里时，规则复用、组合和测试都会变困难。',
            'scenario' => '优惠券是否可用判断。',
            'common_usage' => [
                '优惠券系统',
                '权限判断',
                '风控规则',
                '商品筛选',
                '用户资格判断',
                '复杂业务规则组合',
            ],
            'exercise_goals' => [
                '定义规格接口',
                '实现多个具体规格',
                '支持 and / or / not 组合',
                '避免复杂 if/else 堆积',
            ],
            'exercise_content' => [
                'title' => '优惠券可用性规则',
                'description' => '你正在实现优惠券是否可用的判断，规则包括是否过期、订单金额、商品分类、用户等级和新用户限制。',
                'requirements' => [
                    '定义规格契约，每个业务规则独立成一个规格对象。',
                    '支持组合多个规格表达 and、or、not 的复杂条件。',
                    '在 Exercise.php::run() 中演示一个订单同时满足“未过期 + 满 100 元 + 指定分类”。',
                    '补充测试验证单个规则、组合规则和失败原因表达。',
                ],
            ],
            'suggested_classes' => [
                'CouponSpecificationInterface.php',
                'NotExpiredSpecification.php',
                'MinimumAmountSpecification.php',
                'UserLevelSpecification.php',
                'AndSpecification.php',
            ],
            'laravel_connection' => 'FormRequest 适合输入验证，Specification 更偏复杂业务资格和领域规则判断。',
        ],
        [
            'key' => 'iterator',
            'name' => 'Iterator',
            'name_cn' => '迭代器模式',
            'class_name' => 'Iterator',
            'category' => 'behavioral',
            'difficulty' => 'medium',
            'status' => 'todo',
            'summary' => '提供一种统一方式顺序访问集合元素，而不暴露集合内部结构。',
            'problem' => '调用方直接处理分页、游标或文件读取细节时，遍历逻辑难以复用。',
            'scenario' => '分页读取大量订单或日志。',
            'common_usage' => [
                '大数据量分页处理',
                'LazyCollection',
                '文件逐行读取',
                '游标查询',
                '批量任务',
            ],
            'exercise_goals' => [
                '封装集合遍历逻辑',
                '隐藏分页细节',
                '理解 PHP Iterator',
                '对比 Laravel LazyCollection',
            ],
            'exercise_content' => [
                'title' => '分页订单批处理迭代器',
                'description' => '你正在实现一个批处理任务，需要分页读取大量订单或日志，避免一次性加载全部数据。',
                'requirements' => [
                    '设计一个迭代器隐藏分页或游标读取细节。',
                    '调用方只关心逐条处理订单，不关心当前是第几页。',
                    '在 Exercise.php::run() 中演示遍历 3 页模拟订单并统计处理数量。',
                    '补充测试验证空数据、最后一页不足和大批量读取不会一次性加载。',
                ],
            ],
            'suggested_classes' => [
                'OrderCursorIterator.php',
                'PaginatedOrderCollection.php',
                'OrderBatchReader.php',
            ],
            'laravel_connection' => 'Laravel LazyCollection、cursor 和 chunk 都与迭代大数据集合的思想相关。',
        ],
        [
            'key' => 'mediator',
            'name' => 'Mediator',
            'name_cn' => '中介者模式',
            'class_name' => 'Mediator',
            'category' => 'behavioral',
            'difficulty' => 'hard',
            'status' => 'todo',
            'summary' => '通过中介对象协调多个对象交互，减少对象之间直接依赖。',
            'problem' => '多个对象彼此互相调用时，依赖关系会变成网状，任何变化都可能影响多个对象。',
            'scenario' => '表单多个字段联动。',
            'common_usage' => [
                '表单联动',
                '工作流协调',
                '多组件通信',
                '复杂 UI 后端配置',
                '业务对象协作',
            ],
            'exercise_goals' => [
                '减少对象互相调用',
                '创建中介者协调交互',
                '理解中介者和观察者区别',
                '避免中介者变成上帝类',
            ],
            'exercise_content' => [
                'title' => '门店库存筛选联动',
                'description' => '你正在实现一个库存筛选表单，省份、城市、门店和库存结果互相影响，但字段之间不应直接相互调用。',
                'requirements' => [
                    '设计中介者协调省份、城市、门店、库存四个字段或组件。',
                    '字段变化时只通知中介者，由中介者决定其他字段如何更新。',
                    '在 Exercise.php::run() 中演示选择省份后刷新城市和门店范围。',
                    '补充测试验证新增字段不会让旧字段之间产生直接依赖。',
                ],
            ],
            'suggested_classes' => [
                'FormMediator.php',
                'ProvinceField.php',
                'CityField.php',
                'StoreField.php',
                'InventoryField.php',
            ],
            'laravel_connection' => '可用于复杂工作流或后端配置协调，但在 Laravel 中也可以先考虑事件或服务编排。',
        ],
        [
            'key' => 'visitor',
            'name' => 'Visitor',
            'name_cn' => '访问者模式',
            'class_name' => 'Visitor',
            'category' => 'behavioral',
            'difficulty' => 'hard',
            'status' => 'todo',
            'summary' => '在不修改对象结构的前提下，为对象结构增加新的操作。',
            'problem' => '对象结构稳定但操作经常增加时，把所有操作写进节点类会不断污染节点本身。',
            'scenario' => '对不同报表节点执行不同操作。',
            'common_usage' => [
                'AST 处理',
                '报表节点处理',
                '表达式解析',
                '权限扫描',
                '复杂对象结构遍历',
            ],
            'exercise_goals' => [
                '定义访问者接口',
                '不修改节点类的情况下增加操作',
                '理解访问者适合稳定对象结构',
                '理解其复杂度和使用边界',
            ],
            'exercise_content' => [
                'title' => '报表节点操作扩展',
                'description' => '你正在实现一个报表编辑器，报表由文本、图表、表格、筛选器节点组成，需要支持导出、权限扫描和字段统计。',
                'requirements' => [
                    '定义报表节点结构，并保持节点结构相对稳定。',
                    '定义访问者来承载导出、权限扫描或字段统计等新增操作。',
                    '在 Exercise.php::run() 中演示对一个小报表节点树执行字段统计访问者。',
                    '补充测试验证新增操作不需要修改节点类。',
                ],
            ],
            'suggested_classes' => [
                'ReportNodeInterface.php',
                'TextNode.php',
                'ChartNode.php',
                'TableNode.php',
                'ReportNodeVisitorInterface.php',
                'ExportVisitor.php',
            ],
            'laravel_connection' => '适合报表节点、表达式树或 AST 一类结构稳定而操作扩展频繁的场景。',
        ],
        [
            'key' => 'null-object',
            'name' => 'Null Object',
            'name_cn' => '空对象模式',
            'class_name' => 'NullObject',
            'category' => 'behavioral',
            'difficulty' => 'easy',
            'status' => 'todo',
            'summary' => '用一个空对象替代 null，减少空值判断。',
            'problem' => '调用方到处判断 null 会让核心流程变长，也容易漏掉空值分支。',
            'scenario' => '用户没有默认地址时返回空地址对象。',
            'common_usage' => [
                '用户资料',
                '配置读取',
                '权限对象',
                '购物车',
                '默认值处理',
                '避免 null 判断',
            ],
            'exercise_goals' => [
                '定义真实对象和空对象统一接口',
                '用空对象替代 null',
                '减少调用方 if 判断',
                '理解不要滥用空对象隐藏错误',
            ],
            'exercise_content' => [
                'title' => '用户默认地址空对象',
                'description' => '你正在实现结算页地址展示，用户可能没有默认地址，但页面仍需要稳定返回收货人、电话和地址摘要。',
                'requirements' => [
                    '定义地址契约，让真实地址和空地址对象拥有一致方法。',
                    '没有默认地址时返回空地址对象，而不是返回 null。',
                    '在 Exercise.php::run() 中演示有地址用户和无地址用户的结算摘要。',
                    '补充测试验证调用方不需要写多处 null 判断，同时不会隐藏必须报错的场景。',
                ],
            ],
            'suggested_classes' => [
                'AddressInterface.php',
                'UserAddress.php',
                'NullAddress.php',
            ],
            'laravel_connection' => '可用于默认配置、匿名用户、空权限等场景，但不要掩盖本应显式失败的问题。',
        ],
        [
            'key' => 'repository',
            'name' => 'Repository',
            'name_cn' => '仓储模式',
            'class_name' => 'Repository',
            'category' => 'laravel-specific',
            'difficulty' => 'medium',
            'status' => 'todo',
            'summary' => '封装数据访问逻辑，为业务层提供集合式的数据访问接口。',
            'problem' => '复杂查询散落在多个 Service 或 Controller 中时，复用、测试和替换数据源都不方便。',
            'scenario' => '用户数据读取、订单数据读取、复杂查询复用。',
            'common_usage' => [
                'Service 层调用数据访问',
                '复杂查询封装',
                '多数据源切换',
                '测试时替换数据访问实现',
                '领域模型数据获取',
            ],
            'exercise_goals' => [
                '理解 Repository 的价值和争议',
                '简单 CRUD 不强行使用 Repository',
                '复杂查询或多数据源时再使用',
                '对比 Eloquent 直接查询',
            ],
            'exercise_content' => [
                'title' => '订单查询仓储',
                'description' => '你正在实现订单列表查询，业务层需要读取最近已支付订单、按用户筛选订单和查询订单详情。',
                'requirements' => [
                    '定义仓储契约，把复杂查询从业务服务中移出。',
                    '设计 Eloquent 实现和测试替身的边界。',
                    '在 Exercise.php::run() 中演示业务服务通过仓储读取“最近 10 笔已支付订单”。',
                    '补充测试验证业务服务可以替换为内存仓储而不依赖数据库。',
                ],
            ],
            'suggested_classes' => [
                'UserRepositoryInterface.php',
                'EloquentUserRepository.php',
                'OrderRepositoryInterface.php',
            ],
            'laravel_connection' => 'Laravel Eloquent 已经很强，Repository 应该服务于复杂查询复用、多数据源或清晰边界，而不是机械套层。',
        ],
        [
            'key' => 'service-layer',
            'name' => 'Service Layer',
            'name_cn' => '服务层模式',
            'class_name' => 'ServiceLayer',
            'category' => 'laravel-specific',
            'difficulty' => 'easy',
            'status' => 'todo',
            'summary' => '把业务流程从 Controller 中抽离到 Service 层。',
            'problem' => 'Controller 承担业务编排后会变厚，HTTP 层和业务层边界不清晰。',
            'scenario' => '订单创建、支付确认、报表生成。',
            'common_usage' => [
                'Controller 调用业务流程',
                '订单业务',
                '支付业务',
                '用户业务',
                '报表业务',
                '数据同步业务',
            ],
            'exercise_goals' => [
                '保持 Controller 简洁',
                '把业务编排放到 Service',
                '理解 Service 不等于工具类',
                '理解 Service 和 Repository 分工',
            ],
            'exercise_content' => [
                'title' => '订单创建应用服务',
                'description' => '你正在实现下单业务，Controller 只负责接收请求，订单创建、库存扣减、支付单创建和通知由 Service 编排。',
                'requirements' => [
                    '设计一个订单创建服务，表达完整业务流程。',
                    '让 Controller 或 Exercise 只传入已验证的数据并接收业务结果。',
                    '在 Exercise.php::run() 中演示创建订单服务返回订单编号和下一步支付信息。',
                    '补充测试验证 Controller 不包含核心业务分支。',
                ],
            ],
            'suggested_classes' => [
                'OrderApplicationService.php',
                'PaymentConfirmationService.php',
                'ReportGenerationService.php',
            ],
            'laravel_connection' => 'Laravel 项目中最常见的组织方式之一，适合放业务编排，不适合变成静态工具箱。',
        ],
        [
            'key' => 'pipeline',
            'name' => 'Pipeline',
            'name_cn' => '管道模式',
            'class_name' => 'Pipeline',
            'category' => 'laravel-specific',
            'difficulty' => 'medium',
            'status' => 'todo',
            'summary' => '让数据依次经过多个处理步骤，每个步骤处理后交给下一个步骤。',
            'problem' => '多个处理步骤写在一个方法里时，步骤顺序和单步测试都不清晰。',
            'scenario' => '数据处理流水线、请求过滤、导入校验。',
            'common_usage' => [
                'Laravel Pipeline',
                'Middleware',
                '数据导入校验',
                '内容过滤',
                '请求预处理',
                '报表数据加工',
            ],
            'exercise_goals' => [
                '理解多个步骤串联',
                '每个步骤只做一件事',
                '对比责任链模式',
                '理解 Laravel Pipeline 使用场景',
            ],
            'exercise_content' => [
                'title' => '导入数据清洗管道',
                'description' => '你正在实现 CSV 导入前的数据处理，原始行需要依次经过去空格、字段校验、格式标准化、业务补全和持久化准备。',
                'requirements' => [
                    '设计多个 Pipe，每个 Pipe 只处理一件事并把数据交给下一步。',
                    '明确每一步输入输出的数据结构。',
                    '在 Exercise.php::run() 中演示一行原始数据通过清洗管道得到规范化结果。',
                    '补充测试验证步骤顺序、失败中断和单个 Pipe 可独立测试。',
                ],
            ],
            'suggested_classes' => [
                'ImportPipeline.php',
                'TrimRowPipe.php',
                'ValidateRowPipe.php',
                'NormalizeRowPipe.php',
                'PersistRowPipe.php',
            ],
            'laravel_connection' => 'Laravel Pipeline 是框架内置能力，Middleware 也体现了数据沿步骤传递的思想。',
        ],
        [
            'key' => 'event-listener',
            'name' => 'Event / Listener',
            'name_cn' => '事件监听模式',
            'class_name' => 'EventListener',
            'category' => 'laravel-specific',
            'difficulty' => 'easy',
            'status' => 'todo',
            'summary' => '通过事件和监听器解耦主流程和后续动作。',
            'problem' => '主业务流程直接执行通知、积分、日志等后续动作，会导致流程变重且扩展点不清晰。',
            'scenario' => '订单支付成功后通知、积分、日志。',
            'common_usage' => [
                'Laravel Event',
                'Laravel Listener',
                '用户注册',
                '支付成功',
                '订单完成',
                '审批通过',
                '文件上传完成',
            ],
            'exercise_goals' => [
                '理解事件发布',
                '理解监听器响应',
                '对比观察者模式',
                '避免主业务流程过重',
            ],
            'exercise_content' => [
                'title' => '订单支付成功事件分发',
                'description' => '你正在实现 Laravel 风格的事件监听练习，订单支付成功后通过事件触发通知、积分和审计日志。',
                'requirements' => [
                    '设计事件对象承载订单编号、用户编号和支付金额。',
                    '设计多个监听器分别处理通知、积分和审计日志。',
                    '在 Exercise.php::run() 中演示构造事件并列出将要触发的监听器。',
                    '补充测试验证新增监听器不需要修改支付确认服务。',
                ],
            ],
            'suggested_classes' => [
                'OrderPaid.php',
                'SendOrderPaidNotification.php',
                'GrantOrderPoints.php',
                'WritePaymentAuditLog.php',
            ],
            'laravel_connection' => '这是 Laravel 对观察者思想的常用框架化支持，适合把后续动作从主流程拆开。',
        ],
        [
            'key' => 'job-command',
            'name' => 'Job / Command',
            'name_cn' => '任务命令模式',
            'class_name' => 'JobCommand',
            'category' => 'laravel-specific',
            'difficulty' => 'easy',
            'status' => 'todo',
            'summary' => '把耗时任务封装为 Job，交给队列异步执行。',
            'problem' => '耗时任务放在 HTTP 请求中会拖慢响应，也缺少重试、失败记录和后台调度能力。',
            'scenario' => '异步导出报表、发送邮件、生成文件。',
            'common_usage' => [
                'Laravel Queue',
                '报表导出',
                '邮件发送',
                '文件生成',
                '图片处理',
                '数据同步',
            ],
            'exercise_goals' => [
                '理解 Job 和 Command 模式关系',
                '理解同步任务和异步任务',
                '理解重试和失败处理',
                '不在请求中执行耗时操作',
            ],
            'exercise_content' => [
                'title' => '异步报表导出 Job',
                'description' => '你正在实现报表导出任务，请求只创建导出任务记录，真正的文件生成交给 Job 异步执行。',
                'requirements' => [
                    '设计 Job 输入，只传递导出任务 id 或必要的轻量参数。',
                    'Job 内部负责加载查询条件、生成文件、更新进度和记录失败原因。',
                    '在 Exercise.php::run() 中演示同步执行一个模拟导出 Job 的流程摘要。',
                    '补充测试验证任务可重试、失败状态可记录，并且请求流程不阻塞等待文件生成。',
                ],
            ],
            'suggested_classes' => [
                'ExportReportJob.php',
                'SendMailJob.php',
                'GenerateFileJob.php',
            ],
            'laravel_connection' => 'Laravel Job 是命令思想在队列任务中的框架化应用，天然支持队列、重试和失败处理。',
        ],
        [
            'key' => 'form-request-validation',
            'name' => 'Form Request Validation',
            'name_cn' => '表单请求验证',
            'class_name' => 'FormRequestValidation',
            'category' => 'laravel-specific',
            'difficulty' => 'easy',
            'status' => 'todo',
            'summary' => '把请求参数验证逻辑从 Controller 中拆分出去。',
            'problem' => 'Controller 同时处理参数验证和业务编排时，方法会变长且验证规则难以复用。',
            'scenario' => '创建订单、提交表单、接口参数验证。',
            'common_usage' => [
                'Controller 入参验证',
                'API 请求验证',
                '表单提交',
                '后台管理',
                '创建和更新操作',
            ],
            'exercise_goals' => [
                '理解验证逻辑和业务逻辑分离',
                '保持 Controller 简洁',
                '对比 Specification 模式',
                '理解 FormRequest 适合输入验证，不适合复杂业务资格判断',
            ],
            'exercise_content' => [
                'title' => '创建订单请求验证',
                'description' => '你正在实现创建订单接口，请求参数包括商品明细、收货地址、优惠券编号和支付方式，需要先完成输入验证。',
                'requirements' => [
                    '设计 FormRequest 规则，校验商品列表、数量、地址、优惠券格式和支付方式。',
                    '把输入验证从 Controller 中移走，Controller 只接收 validated 数据。',
                    '在 Exercise.php::run() 中演示一组合法请求和一组缺少地址的非法请求摘要。',
                    '补充测试验证必填、类型、枚举值和嵌套数组校验。',
                ],
            ],
            'suggested_classes' => [
                'StoreOrderRequest.php',
                'UpdateProfileRequest.php',
                'SubmitFormRequest.php',
            ],
            'laravel_connection' => 'Laravel FormRequest 是输入验证的标准入口，复杂业务资格判断仍应放到领域规则或服务中。',
        ],
    ];

    private const NEXT_ORDER = [
        'strategy',
        'simple-factory',
        'factory-method',
        'adapter',
        'decorator',
        'observer',
        'command',
        'facade',
        'specification',
        'state',
        'chain-of-responsibility',
        'template-method',
        'builder',
        'composite',
        'proxy',
        'abstract-factory',
        'bridge',
        'data-mapper',
        'dependency-injection',
        'repository',
        'service-layer',
        'pipeline',
        'iterator',
        'mediator',
        'visitor',
        'null-object',
        'prototype',
        'singleton',
        'fluent-interface',
        'registry',
        'event-listener',
        'job-command',
        'form-request-validation',
    ];

    /**
     * @return array<int, array<string, mixed>>
     */
    public function all(): array
    {
        return array_map(
            fn (array $pattern): array => $this->enrich($pattern),
            self::PATTERNS
        );
    }

    /**
     * @return array<string, array<string, string>>
     */
    public function categories(): array
    {
        return self::CATEGORIES;
    }

    /**
     * @return array<string, mixed>|null
     */
    public function find(string $key): ?array
    {
        $key = $this->normalizeKey($key);

        foreach (self::PATTERNS as $pattern) {
            if ($pattern['key'] === $key) {
                return $this->enrich($pattern);
            }
        }

        return null;
    }

    public function definition(string $key): ?PatternDefinition
    {
        $pattern = $this->find($key);

        return $pattern === null ? null : PatternDefinition::fromArray($pattern);
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    public function byCategory(string $category): array
    {
        $category = $this->normalizeKey($category);

        if (! array_key_exists($category, self::CATEGORIES)) {
            return [];
        }

        return array_values(array_filter(
            $this->all(),
            fn (array $pattern): bool => $pattern['category'] === $category
        ));
    }

    /**
     * @return array<string, mixed>|null
     */
    public function next(): ?array
    {
        foreach (self::NEXT_ORDER as $key) {
            $pattern = $this->find($key);

            if ($pattern !== null && $pattern['status'] === 'todo') {
                return $pattern;
            }
        }

        return null;
    }

    private function normalizeKey(string $key): string
    {
        return str_replace('_', '-', strtolower(trim($key)));
    }

    /**
     * @param  array<string, mixed>  $pattern
     * @return array<string, mixed>
     */
    private function enrich(array $pattern): array
    {
        $category = self::CATEGORIES[$pattern['category']];

        return $pattern + [
            'category_name' => $category['name'],
            'category_cn' => $category['name_cn'],
            'category_directory' => $category['directory'],
            'doc_path' => sprintf('app/PatternLab/%s/%s/PATTERN.md', $category['directory'], $pattern['class_name']),
            'exercise_path' => sprintf('app/PatternLab/%s/%s', $category['directory'], $pattern['class_name']),
            'test_path' => sprintf('tests/Unit/PatternLab/%s/%sTest.php', $category['directory'], $pattern['class_name']),
        ];
    }
}
